name: Build and Deploy Production

on:
  release:
    types: [published]

jobs:
  build-and-deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn install
          yarn build
          rm -rf /build/admin

      - name: Add version info ðŸ“„
        id: version-info
        run: |
          node version-info-generator.js --branch=master --commit=$GITHUB_SHA --build=$GITHUB_RUN_NUMBER > build/version.json

      - name: Deploy Gesund-Zusammen.de ðŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          BASE_BRANCH: source
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Removes old (hashed) files

  build-and-deploy-production-2:
    needs: build-and-deploy-production
    runs-on: ubuntu-latest
      steps:
          - name: repo-sync
            uses: wei/git-sync@v1
            env:
              SOURCE_REPO: 'https://manzke:${{secrets.GH_ACCESS_TOKEN }}github.com/gesund-zusammen/gesund-zusammen.git'
              SOURCE_BRANCH: 'master'
              DESTINATION_REPO: 'https://manzke:${{secrets.GH_ACCESS_TOKEN }}github.com/gesund-zusammen/healthy-together.git'
              DESTINATION_BRANCH: 'master'
